# fly.toml app configuration file generated for incrustado-laravel on 2023-07-20T10:31:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "incrustado-laravel"
primary_region = "scl"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  IZIPAY_USERNAME = "44532503"
  IZIPAY_PASSWORD = "testpassword_x0ZDVlzhOnkCMiSGpOQ9rLbQUlKYmunHSfI5SN54avffE"
  IZIPAY_ENDPOINT = "https://api.micuentaweb.pe"
  IZIPAY_PUBLIC_KEY = "44532503:testpublickey_csSdGM0KnIzIy0hYRj29NoDYjBKV6uDAfP42sIonUhG7u"
  IZIPAY_CLIENT_ENDPOINT = "https://static.micuentaweb.pe"
  IZIPAY_SHA256_KEY = "WLYdcwRkqenw7j9hgKmZU4yhQ91gnqQ36S95YwBh7ByE8"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
